name: Build and deploy test system

on:
  push:
    branches: 
      - "testbranch"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    #- name: Build the Docker image
     # run: echo "sandevdsic123" | sudo -S sudo docker build . --file Dockerfile --tag management-fronend-testbranch-image:latest
    #- name: stop current system
    #  run: echo "sandevdsic123" | sudo -S sudo docker compose down
    #- name: Execute dokcer compose file
     # run: echo "sandevdsic123" | sudo -S sudo docker compose up -d
    - run: npm ci
    - run: npm build --if-present
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
